### ISSUE TITLE
When delting a record in openshift wordpress I get an error Call to undefined method

### ISSUE THREAD

**Issue by supaxi** [tabulate/tabulate#11]
Fatal error: Call to undefined method WordPress\Tabulate\Controllers\RecordController::delete() in /var/lib/openshift/account/app-root/data/plugins/tabulate/src/Menus.php on line 94

Is there an include I need to add to the template to get the delete to work properly?  I am new to wordpress and openshift.

Thanks!

**Comment by samwilson** [comment]
Indeed, there is a bug in record-deleting! However, I fixed it on Friday, and am just going to do a bit more testing this morning (UTC+8) before releasing a new version. So stand by and all should be fine later today. :)

Thank you for taking the time to report this issue!

**Comment by samwilson** [comment]
Okay, version 0.20.0 has been tagged and should address the *deleting* issue. Could you upgrade and let me know if things work correctly for you? Thanks. :)

**Comment by samwilson** [comment]
Has this issue been fixed now? Does record-deleting work correctly for you?

**Comment by supaxi** [comment]
Yes, I am able to delete now.  Thanks!!

**Comment by samwilson** [comment]
Cool! :) I'm glad.
