### ISSUE TITLE
Call to undefined function WordPress\Tabulate\is_plugin_active()

### ISSUE THREAD

**Issue by arjun05** [tabulate/tabulate#16]
I always encounter this error every updates

Fatal error: Call to undefined function WordPress\Tabulate\is_plugin_active() in .../wp-content/plugins/tabulate/src/Menus.php on line 118

**Comment by samwilson** [comment]
Thanks for reporting this! Sorry it's not working smoothly. I'll try and get this fixed this afternoon.

What version of WordPress are you using?

**Comment by arjun05** [comment]
I'm using WordPress 4.2.3

**Comment by samwilson** [comment]
I've added a check for the existance of this function. This basically just means that the ERD menu item won't appear when Tabulate is being activated or upgraded, but I don't think that really matters. It could be arranged to work correctly though, if it's worth it.

Let me know if 1.0.2 fixes it for you.

**Comment by samwilson** [comment]
Please re-open if you're still having this issue. Thanks!

**Comment by arjun05** [comment]
Fixed already, Thanks.
