### ISSUE TITLE
Cannot insert data when the primary key is of type varchar

### ISSUE THREAD

**Issue by kcdipesh** [tabulate/tabulate#17]
Received following error

   
   Argument 2 passed to WordPress\Tabulate\DB\ChangeTracker::after_save() must be an instance of WordPress\Tabulate\DB\Record, boolean given, called in ... /plugins/tabulate/src/DB/Table.php on line 966 and defined, .../plugins/tabulate/src/DB/ChangeTracker.php, 69,

**Comment by samwilson** [comment]
Thanks for reporting this. Working on it now.

**Comment by samwilson** [comment]
This should be fixed now, in 1.0.3. Can you please test?

Thanks again!

**Comment by kcdipesh** [comment]
Awesome, it is now working.  And thank you for a great plugin!!!
