### ISSUE TITLE
INSERT bug when Create a row: some types do not get inserted and need to be updated later

### ISSUE THREAD

**Issue by PacoBlanca** [tabulate/tabulate#21]
When Create a new row for a table, in the very INSERT of it. It works, the record is inserted, but not all the values are inserted.

The pk and all the string type are fine, but the numeric staff, that is some NUMERIC (x,y) and so on, also an ENUM('0','1') do not get inserted.

No big problem because the UPDATE goes smooth on the other side, but it is a bug, Sam.

**Comment by samwilson** [comment]
Sorry about this Paco!

I've been trying to figure it out, but with no luck; I can't replicate your bug. Sorry!

Can you give me the `CREATE TABLE` statement for the table you're getting these errors with? Then I'll dig further.

I'll be able to work on it more after the weekend — then, I shall get it fixed! Thanks for your patience.

**Comment by PacoBlanca** [comment]
I were looking and I think the insert problem it's not about types
because my penultimate column it's a string and don't get inserted too.

Curious thing it's that updates goes perfect. The real thing is that only the first 3 columns get inserted. Maybe some filter on $columns or $data or a bad loop you did, I don't know really.

All tables with more than 3 columns have insert problems, a try here:

CREATE TABLE IF NOT EXISTS pb_servicio (
s_id VARCHAR(4) NOT NULL COMMENT 'código identificador del servicio',
s_nom VARCHAR(80) NOT NULL COMMENT 'nombre del servicio',
s_des TEXT COMMENT 'texto con información/condiciones/descripción del servicio',
s_pre NUMERIC (10,2) NOT NULL DEFAULT '0' COMMENT 'precio por persona del servicio',
s_iva NUMERIC (3,2) NOT NULL DEFAULT '0.21' COMMENT 'IVA del artículo -por defecto el 21%-',
s_dto NUMERIC (3,2) NOT NULL DEFAULT '0' COMMENT 'si es 0.5, tiene un descuento del 50%',
s_tsini TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'timestamp con la fecha de creación del servicio',
s_tsfin TIMESTAMP COMMENT 'timestamp con la fecha de la desactivación del servicio',
s_img VARCHAR(160) COMMENT 'url o dirección del fichero de imagen asociado al servicio',
s_bitblo ENUM('0','1') NOT NULL DEFAULT 0 COMMENT 'activación(0)/bloqueo(1) del servicio',
CONSTRAINT servicio_pk PRIMARY KEY(s_id)
)
ENGINE InnoDB
COMMENT 'producto concertado con un proveedor o proveedores';


Best regards, yours sincerely,
Paco Blanca

**Comment by samwilson** [comment]
I'm still having trouble replicating this, sorry! What data are you inserting? I've created your table as above (except for the default value; see below), and can create records in it correctly for all columns.

What version of MySQL are you using? What about [strict mode](http://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_strict_mode)?

----
There's a small typo in your `CREATE TABLE` statement:
```sql
s_bitblo ENUM('0','1') NOT NULL DEFAULT 0 COMMENT 'activación(0)/bloqueo(1) del servicio',
```
should be
```sql
s_bitblo ENUM('0','1') NOT NULL DEFAULT '0' COMMENT 'activación(0)/bloqueo(1) del servicio',
```
with quotation marks around the default value.
