### ISSUE TITLE
Can I make a page like tabulate?

### ISSUE THREAD

**Issue by feelpassion** [tabulate/tabulate#25]
Hi,

I want to make a page like the screenshot of tabulate.
I want to see the table of database and modify it.

Could you tell me about it?

Thank you.

**Comment by samwilson** [comment]
You should be able to create a new table from the Tabulate overview screen. Do you see a 'Create a new table' text field? Enter the name of your new table there, click 'Create', and you'll be taken to the table-structure editing screen. Now you can add whatever columns you want.

Then, it's just a matter of either creating one-by-one, or importing, whatever data you want in there. :-)

**Comment by samwilson** [comment]
(Oh, and sorry for the delay in replying to you! I only just saw this.)

**Comment by samwilson** [comment]
Let me know if you need any more help. :-)
