### ISSUE TITLE
“Overview” and “Reports” in 2.5.1 not working :-(

### ISSUE THREAD

**Issue by chadderksen** [tabulate/tabulate#27]
Only “Grants” page is working for me.. “Overview” and “Reports” are not working, just white pages… I have tried to 

- disable all other plugins, still no luck. 
- Also after a Google quest i did not find my answer

Can somebody please help to find my answer to get Tabulate 2.5.1. to work?

Thnx up front!

Chad

**Comment by samwilson** [comment]
Sorry to hear it!

Can you try enabling [debugging](http://codex.wordpress.org/WP_DEBUG) by putting `define( 'WP_DEBUG', true );` into your `wp-config.php` file? That might make it spit out an error message that will tell us what's going on.

**Comment by chadderksen** [comment]
Thnx for your quick reply…. My shared hosting provider has php 5.3 is it possible i need a newer version? I a different server, there its working….

**Comment by samwilson** [comment]
Hm, yes I'm afraid that could well be the problem. WordPress in general [requires](https://wordpress.org/about/requirements/) PHP 5.6, and so Tabulate isn't tested on anything below that. PHP 5.3 itself has been end-of-life for 1.5 years; I reckon you should hassle your host to upgrade! :)
