### ISSUE TITLE
Report menu give fatal error

### ISSUE THREAD

**Issue by iozcelik** [tabulate/tabulate#29]
Hello, when I pressed Report menu, gives an error like that:
**Fatal error: Call to undefined method Twig_Environment::createTemplate() in /home/content/**

I can see Grants and Overview menu. I use Php 5.4. 

I just want to shown html tables for my query, it is not to be hard :(

**Comment by samwilson** [comment]
I'm afraid I can't replicate this error. Do you have any other information? What version of WordPress are you using? What version of Tabulate?

I suspect it's a PHP version incompatibility — WordPress [requires](https://wordpress.org/about/requirements/) PHP 5.6 or above, so Tabulate isn't tested on anything below that.

Sorry I'm not more help! I'll keep investigating though.
