### ISSUE TITLE
Select a record not using the primary identifyer when using shortcodes.

### ISSUE THREAD

**Issue by ThomasJ2015** [tabulate/tabulate#30]
Could anyone please assist me in modifying the code in such a way that instead of selecting a record based on the primary identifier (which is passed as 'ident' in the shortcode) it can be used to select a record using a different identifier also passed using a short code.
Example:
`[tabulate format=record table=bookings ident=2]`
 Would return one value from the table bookings where the primary identifier is 2.
Goal:
`[tabulate format=record table=bookings ref=ref-142536]`
And the goal would be for this to return the record that has the reference 'ref-142536'
Any contributions would be greatly appreciated :)
(Also first issues ever)

**Comment by samwilson** [comment]
There are a couple of options for this:

1. You could modify your `bookings` table to drop the `id` primary key and instead set your `ref` column (a `varchar`?) to be the PK.
2. Create a view of your `bookings` table that renames the `ref` column to be `id`, such as:

        CREATE OR REPLACE VIEW current_bookings AS
        SELECT ref AS id, date_booked FROM bookings

Do either of these work for you? There are a few ideas floating around about how to improve the `record` shortcode format, so do let us know your ideas—they can probably be made to happen!

**Comment by samwilson** [comment]
Oh, and if you go the view route, you could be fancier and rename the `id` column to include the prefix:

    CONCAT('ref-',id) AS ref

**Comment by ThomasJ2015** [comment]
Wow @samwilson, They never even crossed my mind. Thanks for your support

**Comment by samwilson** [comment]
No worries!

Do raise more tickets for any future issues you may encounter. I'm keen to make Tabulate as good as possible.
