### ISSUE TITLE
table second page issue

### ISSUE THREAD

**Issue by exchanger01** [tabulate/tabulate#33]
Fatal error: Class 'WordPress\Tabulate\Controllers\Controller' not found in /home/u6692146/public_html/wp-content/plugins/tabulate/src/Menus.php on line 136
i am gettting this error. What should i do ?

**Comment by samwilson** [comment]
This may have been fixed in the recent update. If not, can you provide:
# the URL of page you were on before you got this message,
# what you clicked to move from that page,
# and the URL of the page on which you're getting this error?

(Replace your domain name with 'example.org' if you like.)

**Comment by samwilson** [comment]
I think we can assume this has been fixed now. Please do open a new issue if the problem remains!
