### ISSUE TITLE
Parse error: syntax error, unexpected....

### ISSUE THREAD

**Issue by buddha241** [tabulate/tabulate#37]
Good Afternoon,

I have installed Tabulate and WP Rest API and when I click on overview from the menu it give me this error: 
Parse error: syntax error, unexpected '[' in /home/dimo/public_html/wp-content/plugins/tabulate/src/DB/Column.php on line 554

I also get this error on the reports link, but not on the grants link. 

I have made a test page to use the shortcode:
http://dimo.com/test-2/

and same error, any help would be appreciated. THank you. 
-SGF

**Comment by samwilson** [comment]
Sorry about the bug! Thanks for reporting.

What version of PHP are you using? I think this could be a pre-5.4 issue.

**Comment by buddha241** [comment]
I am currently using version 5.4.45, do you recommend updating to a different version? 

thanks.
-SGF

**Comment by buddha241** [comment]
Ok so I changed my php configuration so that .php file extension will be processed by 5.4 and it works.

on the table now I get this error when I go through the different pages to view all the parts, any way to just hide the list and just show the results when they search for a one of my part numbers? 
Fatal error: Class 'WordPress\Tabulate\Controllers\Controller' not found in /home/dimo/public_html/wp-content/plugins/tabulate/src/Menus.php on line 136

**Comment by samwilson** [comment]
That error about the controller may have been fixed in the most recent version; can you try updating and see if it persists?

There isn't currently anyway to hide the data results until the search form has been submitted, but that's a good idea; could you please raise a separate issue for it.

**Comment by samwilson** [comment]
This seems to have been fixed.
