### ISSUE TITLE
Cannot reorder columns in Tabulate Wordpress Plugin

### ISSUE THREAD

**Issue by jdenning** [tabulate/tabulate#40]
Version 2.7.13 In Overview the up-down arrows will move a given column but when I hit the save button the moved row returns to its original position. The row was added to the table and originated at the bottom. It consists of a phone number as a short-text 255 and is not a key or auto-incrementing.

**Comment by samwilson** [comment]
I'll have a look at this today. Sorry for the defect! :-( Hopefully won't be too hard to fix.

Thanks for reporting it. :-)

**Comment by samwilson** [comment]
Sorry about the delay here, but I think this is now fixed. Can you please upgrade to 2.8.2 and see how it goes? Thanks!!
