### ISSUE TITLE
Example shortcode

### ISSUE THREAD

**Issue by gcraig1006** [tabulate/tabulate#41]
New to Tabulate - and not very experienced.  I am confused by the shortcode attributes and their proper formats.

If I could just get an example shortcode to do this one thing I think it will sink in!

I have a table called
Xwp Participants Database

I just want to give the user a form where he can create a new record in that table.

Could someone just please tell me what that shortcode should be?

Very much appreciate your help!

**Comment by samwilson** [comment]
Did you create the table using Tabulate's table-structure editor? If not, does your table have spaces in its name? Anyway, the shortcode should be one of these:

    [tabulate format="form" table="xwp_participants_database"]
    [tabulate format="form" table="Xwp Participants Database"]

Probably the first one, without spaces.

Do you get any error when you put that into a post or page?

Don't forget to make sure that the user using the form has been granted rights to create records in that table (in the 'Grants' tab of Tabulate).

**Comment by samwilson** [comment]
See also the docs: http://tabulate.readthedocs.io/en/latest/shortcode.html#form-format

**Comment by gcraig1006** [comment]
Thanks, Sam

I was actually trying to use Tabulate to handle data in a table generated
by a different plugin ("Participants").

When I created a sample table using Tabulate the shortcode worked OK.

Thanks again for helping me clear it up.

Gary



  <https://mailtrack.io/>Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=garyrcraig@gmail.com&idSignature=22>
