### ISSUE TITLE
Foreign Key, Column, CSS

### ISSUE THREAD

**Issue by shifamalik** [tabulate/tabulate#42]
Hello Team,
Thanks for the great job with the plugin.

I'm new to using it. I have few queries

1. Please let me know how I can get data from two tables using foreign key.
2. Is it possible to decide which all columns to be displayed in the list and form
3. Can we customize the style (CSS)

**Comment by samwilson** [comment]
Glad you like it! Sorry development has been so slow this last year. :(

1. You need to create a view that joins the tables.
2. Again, a view will let you do that (and give you alternative authorisation options at the same time).
3. In the admin-side? No. :( In the front-end? Yep, you can change things in your theme all you want! :)

**Comment by shifamalik** [comment]
Thanks a lot for your quick response. I shall try View and get back to you if I have any queries

**Comment by samwilson** [comment]
Good luck. :)
