### ISSUE TITLE
Tabulate shortcode error

### ISSUE THREAD

**Issue by billsoranno** [tabulate/tabulate#44]
When I use the shortcode like this:
[tabulate table=wp_csw_mbracct_personuser]
I get the following error:
_Tabulate shortcode error:
The 'table' attribute must be set. Attributes found: [ 0 = "</span>" 1 = "" 2 = "" 3 = "style="font-family:" 4 = "Courier" 5 = "" 6 = "class="pre">" ]
For more information, please read the docs._

The documentation does not mention anything about table attributes.

**Comment by samwilson** [comment]
I think this is a result of coping and pasting from the documentation, unfortunately.

See the difference between these two shortcodes:

![widgetdiff](https://cloud.githubusercontent.com/assets/213655/24282085/59105b72-1098-11e7-9f85-49fda0635d61.png)

If you switch to text-mode editing:

![tabs](https://cloud.githubusercontent.com/assets/213655/24282083/590950b6-1098-11e7-9df8-d09e05b607d6.png)

This is how those two short codes actually look:

![code](https://cloud.githubusercontent.com/assets/213655/24282084/590d847e-1098-11e7-90a6-6ca50755486c.png)

This is not a problem limited to Tabulate, it seems.

I'll add a note to the documentation, and the longer-term fix for this is to add a shortcode-insertion button (#45).

**Comment by samwilson** [comment]
I've added to the documentation a mention of the "paste as text" button; it will get around this problem.

**Comment by hheecc** [comment]
Hello Sam.
I inserted a shortcode asking for login before the tabulate shortcode.
When I login with a user with Admin Role, Tabulate works ok showing the table, etc. but if I try to log in with another role (editor for example) it shows 
Tabulate shortcode error:
For more information, please read the docs. 

In the documentation they say ...
Do note that if a table is not accessible to the browsing user then nothing will be displayed. Keep in mind that you can grant access to non-logged-in users to view tables if you wish (via the Grants page in the Admin Area).

But I don't see anything to setup in that "Grant" area
Could you help me?
Thanks

**Comment by samwilson** [comment]
If it's an error, then it's probably not because of grants. Are you entering the shortcode in the source view (as mentioned above)? Can you add a screenshot here of your page in the edit form?

**Comment by samwilson** [comment]
Also, please use #59 for discussing this if it's the same issue; this issue is closed.
