### ISSUE TITLE
Data can be read from the db table but updates fail

### ISSUE THREAD

**Issue by bee7er** [tabulate/tabulate#47]
Everything looks good, but after updating a row the data is not updated in the database and the row reverts to its original value.

If this is to do with 'secure_file_priv' then I don't think it is possible for me to use the product because my hosting company does not allow access to the MySQL ini file.

Please advise.
Thanks

**Comment by samwilson** [comment]
Sorry about the trouble. Can you please provide more information about where (admin or front-end) you're entering the data? What is your table structure? What data are you trying to modify? Do you get any error messages?

Do you get any entry in the table's history log after you try to edit a row?

Does this problem happen on every table, or just some?

Thanks! I'm sure we can get this fixed.

(Oh, and no, `secure_file_priv` is only to do with exporting CSVs.)

**Comment by bee7er** [comment]
Hi SamThank you for responding so quickly.  I really would like your plugin to work, and I'm glad to hear that it is nothing to do with the MySQL ini setting.
Using Tabulate 2.8.2
I have found the problem.  There are no database tables for the Tabulate plugin.  In the error log i get the following message:
    'PHP message: WordPress database error Table 'mydb.wp_tabulate_changes' doesn't exist for query SELECT cs.id AS changeset_id, ...'

There are no tables starting 'wp_tabulate'.
That should help.  What do I do?
ThanksBrian
=========
Below is the procedure I went through:
I have a custom table in my database called 'site-list'.  Note that the nam has a hyphen in it...perhaps this is the culprit.
In the admin area I click on Grants and give myself (admin) all privileges to the site-list table.
Then I click on Overview.
Then I click on 'Site-list' in the list of database tables.
There are 44 records in the table.  
I click 'Edit' against the top row, and change one of the fields. 
I click 'Save'.  The application thinks about it, then redisplays the row, but the updated field is back to its original value.
I go into mysql directly and check the top row of the table, and it is unchanged.
No error message on the web page.
There is no History entry, even though I added a comment when saving.
*** Interestingly, the Delete function works!!!   So, it is not permissions or general access to the table.



 

    On Wednesday, 29 March 2017, 23:57, Sam Wilson <notifications@github.com> wrote:
 

 Sorry about the trouble. Can you please provide more information about where (admin or front-end) you're entering the data? What is your table structure? What data are you trying to modify? Do you get any error messages?Do you get any entry in the table's history log after you try to edit a row?Does this problem happen on every table, or just some?Thanks! I'm sure we can get this fixed.(Oh, and no, secure_file_priv is only to do with exporting CSVs.)—

**Comment by samwilson** [comment]
Thanks for such good information!

So it sounds like there's an issue with activation of Tabulate, because that's when the tabulate tables are created. So first thing is to try deactivating and then reactivating; that won't disturb your custom table or grants or anything, but should create the change-tracking tables.

If that doesn't work... well, let me know if it doesn't, and I'll look into making the activation process more robust. There's some ideas floating around that plugins shouldn't even *do* activation stuff, but check their status at other times, or perhaps have an explicit 'upgrade' button... I don't really know what's best.

Oh, and it'd make sense that delete would work and update not, because the update is wrapped in a transaction that includes updating the change-tracking tables, whereas delete... oh, no, it's the same... hm, well anyway that's a thought for after breakfast.... :-)

**Comment by bee7er** [comment]
Hi SamI put a tail on the error log and then deactivated and re-activated Tabulate.  No error messages in the log and sadly no wp_tabulate tables in the database.
I have installed Tabulate 2.8.2 on two different hosting sites and am now testing it on localhost. I have been getting the same behaviour in all three environments.
Since I am working locally you can send me a debug version if that will help.  We can track down the issue pretty quickly, I am sure.
CheersBrian 

    On Friday, 31 March 2017, 2:11, Sam Wilson <notifications@github.com> wrote:
 

 Thanks for such good information!So it sounds like there's an issue with activation of Tabulate, because that's when the tabulate tables are created. So first thing is to try deactivating and then reactivating; that won't disturb your custom table or grants or anything, but should create the change-tracking tables.If that doesn't work... well, let me know if it doesn't, and I'll look into making the activation process more robust. There's some ideas floating around that plugins shouldn't even do activation stuff, but check their status at other times, or perhaps have an explicit 'upgrade' button... I don't really know what's best.Oh, and it'd make sense that delete would work and update not, because the update is wrapped in a transaction that includes updating the change-tracking tables, whereas delete... oh, no, it's the same... hm, well anyway that's a thought for after breakfast.... :-)—

**Comment by bobmagness** [comment]
I am having the same issue.  The two tables created during activation are not being created.  I have uploaded the latest version of Tablulate on WP 4.7.3 and theme Healthcare.  Would like to try creating the two table with phpMyadmin.  I need the exact names of the two tables (wp_tabulate_reports and changesets I think?) and their columns if that is available somewhere.

I disabled all other plugins and tried deactivation and then activation more than once.

Thanks for the plugin and your common sense responses found above.

Happy Monday Bob

**Comment by samwilson** [comment]
Okay, so it seems that this all results from a foolishness on my part of trying to avoid an [issue](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/881) I ran into with the name of the activation hook. I'll change things around and go with the normal system, and change the test to not have the offending hook name.

Stay tuned. :-)

**Comment by samwilson** [comment]
Please upgrade to 2.8.3 and see if the activation process works now. Thanks for your patience! :)

**Comment by bobmagness** [comment]
Upgraded to 2.8.4 and the deactivate, then reactivate process seemed to work as designed.  The two new tables were created and base functionality seemed to be working.  I will test all of the features that you built into the plugin and give you a head's up if there is anything else.

Thanks again for the plugin and your timely support.

Do you have a list of user requested enhancements that you find interesting and important?  As I test I can keep those requests in mind and look at the plugin code to see where they might fit.

Bob

**Comment by bee7er** [comment]
Hi SamVersion 2.8.4 fixes the problem.
Thank youBrian 

    On Tuesday, 4 April 2017, 3:47, Sam Wilson <notifications@github.com> wrote:
 

 Please upgrade to 2.8.3 and see if the activation process works now. Thanks for your patience! :)—

**Comment by samwilson** [comment]
Great! Thank you to both of you.

> Do you have a list of user requested enhancements that you find interesting and important? As I test I can keep those requests in mind and look at the plugin code to see where they might fit.

Just the feature requests here, and a list in [CONTRIBUTING.md](https://github.com/tabulate/tabulate/blob/master/CONTRIBUTING.md#ideas-for-future-development). Thanks for looking at things! Feel free to create new issues for anything you want.
