### ISSUE TITLE
upgrade to 2.9.1 breaks site.

### ISSUE THREAD

**Issue by bill-goadvntr** [tabulate/tabulate#48]
After update to 2.9.1 I get the following error:
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/wshstreasurer/public_html/wp-content/plugins/tabulate/src/Menus.php on line 54

Please fix!
I will be removing until fixed.

**Comment by samwilson** [comment]
What version of PHP are you running? It sounds like it might be less than 5.5, which became end-of-life in the middle of last year.

There are various parts of Tabulate that rely on modern PHP, but the error you report above is a minor one, and we can update to work around this. Stay tuned for a new version later today.

Sorry about this problem! Thanks for reporting it.

**Comment by samwilson** [comment]
This should be fixed now; please upgrade and report back if things are still failing.
