### ISSUE TITLE
Class 'WP_Filesystem_Base' not found -- on multisite network activation

### ISSUE THREAD

**Issue by kevinsullivan** [tabulate/tabulate#49]
I'm running a stable, completely up to date multisite. I installed Tabulate but am unable to network active it. I receive the message, "Fatal error: Class 'WP_Filesystem_Base' not found in /var/www/html/<mysite./wp-admin/includes/class-wp-filesystem-direct.php on line 17. The plugin also fails to activate on a subsite, with the same error.

**Comment by samwilson** [comment]
Tabulate is, as you've discovered, not fully tested on multisite installations! Sorry about this. I think it shouldn't be too hard to fix this; I'll try to get it done soon. Thanks for reporting this bug!

**Comment by samwilson** [comment]
This should be fixed now, in version 2.9.4. Please reopen this issue if it's not. Thanks!
