### ISSUE TITLE
Nullable Foreign Keys can not be reset to NULL

### ISSUE THREAD

**Issue by IlyaSemenov** [tabulate/tabulate#5]
## Steps to reproduce

1. Create two database tables as follows:

    CREATE TABLE wp_test_category (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255));
    CREATE TABLE wp_test_item (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255), category_id INT, FOREIGN KEY (category_id) REFERENCES wp_test_category(id) ON DELETE SET NULL);
	INSERT INTO wp_test_category (name) VALUES ('foo');
	INSERT INTO wp_test_item (name, category_id) VALUES ('bar', 1);

2. Open Tabulate at http://localhost/wp-admin/admin.php?page=tabulate&controller=record&action=save&table=wp_test_item&ident=1

3. Change Category ID field from "foo" to (empty), click Save.

## Expected result

The Category ID is reset to empty value (NULL is stored to the database).

## Actual result

The Category ID remains pointing to "Foo".

## Notes

I traced the problem to [$wpdb->update not supporting NULLs](https://core.trac.wordpress.org/ticket/15158), however I believe until this is fixed upstream this shouldn't prevent Tabulate from handling this situation properly.

**Comment by IlyaSemenov** [comment]
Actually, the problem is wider than that: any update where any field is set to NULL field will silently fail. So it's not only that you can't change foreign keys back to NULL, you also can't change any other field of a record where there is a key already pointing to NULL.

**Comment by samwilson** [comment]
Hm, yes, this is a tricky thing. Your PR fixes for updates, but inserts still are buggy.

Do you think it's a terrible idea to eschew the use of wpdb->insert and ->update entirely, and build the SQL directly? I might have a look at doing that....

**Comment by samwilson** [comment]
Nulls are now working correctly. Do you think this is an okay fix?

Thanks for taking the time to report problems! I really appreciate it. :)

**Comment by IlyaSemenov** [comment]
This looks like a proper decent fix. Thanks for fully taking care of this issue!
