### ISSUE TITLE
Cross Referencing converts to integer after saving

### ISSUE THREAD

**Issue by bibingkagirl** [tabulate/tabulate#53]
I'd like to ask if how come I use cross reference type and select the table, after saving changes, it goes to integer type.

Suppose a dropdown from the table it is referenced to? or is it something in my data? My database is just from the regular wordpress installation and added tables via my sql, and the rest from Create Table from Tabulate itself.

I have access to myphpadmin and mysql.

Hope you can answer dilemma. Thanks!

**Comment by samwilson** [comment]
The integer type is sort of correct, in that it should be an integer *as well* as a cross-reference. It's the latter that's not working correctly, it seems. This sounds like it's not creating the foreign key correctly.

Could you have a look at the table in phpmyadmin, in the 'relations' section of the structure? See if any foreign key exists from your cross-reference to the target table.

Also, could you tell me the names of the tables and fields you're creating? I'll try and replicate this bug locally.

Thanks for reporting this! And sorry about the non-working-ness.

**Comment by bibingkagirl** [comment]
No worries, I'm really looking forward using this plugin as well. 

I've looked through the myphpadmin, and it doesn't have the 'relation views' option.
[Screenshot](https://qas-shared-assets.s3.amazonaws.com/snaps/3ss8jfvp19hehfr) 

Example data:

TableA: Customer
ID - PK
Name - Text
Address - Text
User_ID - Cross Reference to TableB's Primary Key

TableB: Users
ID - PK (to be referenced in user_id from TableA
Email - text
and other text fields...

Should the version of mysql and phpmyadmin matter, [here it is](https://qas-shared-assets.s3.amazonaws.com/snaps/xl5145qxe2l3ow2).

Thank you very much!

**Comment by bibingkagirl** [comment]
Engine Storage should be in InnoDB instead of MyISAM.

This fixed it.

Thanks for the support!
