### ISSUE TITLE
Temp directory

### ISSUE THREAD

**Issue by pmcarond44** [tabulate/tabulate#57]
I'm getting the following error in Windows server : 

Unable to create temporary export file:
c:/phptemp/tabulate_5a16a1d7437a0.csv

Please advise.

**Comment by samwilson** [comment]
Have you investigated the reasons outlined in https://tabulate.readthedocs.io/en/latest/faq.html#what-reasons-exist-for-the-unable-to-create-temporary-export-file-error ?

**Comment by pmcarond44** [comment]
Hi Sam, 

 

Thank you for this fast reply.

I regret to say I could not solve this easily.
Adding a line to the wp-config.php did not help.
Since I have switched to Database Browser.

 

Regards,

 

Philippe M. Caron

 <http://be.linkedin.com/in/caronphilippe> 

Zaakvoerder



Founded in 1979 !

New adress : Koophandelsplein 5, bus 1,

9000 Gent 

Belgium

VAT BE 419.156.004

 

Gsm +32 475 45 30 30

 <mailto:pmcaron@dataconsult.com> pmcaron@dataconsult.com

New blog :  <http://www.dataconsult.eu/> www.dataconsult.eu

 

Van: Sam Wilson [mailto:notifications@github.com] 
Verzonden: donderdag 23 november 2017 12:12
Aan: tabulate/tabulate <tabulate@noreply.github.com>
CC: pmcarond44 <pmcaron@dataconsult.com>; Author <author@noreply.github.com>
Onderwerp: Re: [tabulate/tabulate] Temp directory (#57)

 

Have you investigated the reasons outlined in https://tabulate.readthedocs.io/en/latest/faq.html#what-reasons-exist-for-the-unable-to-create-temporary-export-file-error ?

**Comment by samwilson** [comment]
Well, if you want a hand debugging this, let me know! :)

(By the way, what is Database Browser?)

**Comment by pmcarond44** [comment]
Hello Sam, 

 

Grant FILE privilege did it.
Although I have never done that before …

 

Thanks.

 

Philippe M. Caron

 <http://be.linkedin.com/in/caronphilippe> 

Zaakvoerder



Founded in 1979 !

New adress : Koophandelsplein 5, bus 1,

9000 Gent 

Belgium

VAT BE 419.156.004

 

Gsm +32 475 45 30 30

 <mailto:pmcaron@dataconsult.com> pmcaron@dataconsult.com

New blog :  <http://www.dataconsult.eu/> www.dataconsult.eu

 

Van: Sam Wilson [mailto:notifications@github.com] 
Verzonden: donderdag 23 november 2017 12:54
Aan: tabulate/tabulate <tabulate@noreply.github.com>
CC: pmcarond44 <pmcaron@dataconsult.com>; Author <author@noreply.github.com>
Onderwerp: Re: [tabulate/tabulate] Temp directory (#57)

 

Well, if you want a hand debugging this, let me know! :)

(By the way, what is Database Browser?)

**Comment by samwilson** [comment]
Oh good, I'm glad it worked!

The FILE permission is required because it uses the more efficient MySQL-internal way of exporting CSV, rather than piping all the data though PHP.

**Comment by pmcarond44** [comment]
Thanks Sam, 

Very efficient service !!!



Regards,

 

Philippe M. Caron

 <http://be.linkedin.com/in/caronphilippe> 

Zaakvoerder



Founded in 1979 !

New adress : Koophandelsplein 5, bus 1,

9000 Gent 

Belgium

VAT BE 419.156.004

 

Gsm +32 475 45 30 30

 <mailto:pmcaron@dataconsult.com> pmcaron@dataconsult.com

New blog :  <http://www.dataconsult.eu/> www.dataconsult.eu

 

Van: Sam Wilson [mailto:notifications@github.com] 
Verzonden: vrijdag 24 november 2017 0:53
Aan: tabulate/tabulate <tabulate@noreply.github.com>
CC: pmcarond44 <pmcaron@dataconsult.com>; Author <author@noreply.github.com>
Onderwerp: Re: [tabulate/tabulate] Temp directory (#57)

 

Oh good, I'm glad it worked!

The FILE permission is required because it uses the more efficient MySQL-internal way of exporting CSV, rather than piping all the data though PHP.
