### ISSUE TITLE
User with editor role got Tabulate shortcode error 

### ISSUE THREAD

**Issue by hheecc** [tabulate/tabulate#59]
When i have a logged user with editor role I got Tabulate shortcode error:.
With administrator role it works ok.
What can I do?

**Comment by samwilson** [comment]
What is the error message? Or do you mean it's just that, an empty message?

**Comment by samwilson** [comment]
This sounds like it is a permissions issue: that the table in question isn't readable by the editor role.

Feel free to re-open if I'm reading this wrong and if you have more information! :)
