### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by psikoz** [tabulate/tabulate#62]
Hey @samwilson @tabulate

I designed a logo. WDYT? If there is a variation you like among them please tell me. I can send a pr if you like.

Logo idea;

-Table/chart and letter T

![tabulate](https://user-images.githubusercontent.com/40601249/42414854-ded77d54-8247-11e8-9ace-20e0f6f105e0.jpg)

**Comment by samwilson** [comment]
Thanks!! That looks really good. I like it, a PR would be well received (put any files in a `assets/logo/` directory).

What do you think of maybe picking some colours similar to the banner we're already using?—

![Tabulate banner](https://ps.w.org/tabulate/assets/banner-772x250.png?rev=1347103)

**Comment by psikoz** [comment]
ofcourse, I tried different variations. Which number do you prefer?

![tabulate](https://user-images.githubusercontent.com/40601249/42418694-3e8bd7ca-82ae-11e8-9430-1dd766ab6473.jpg)

**Comment by samwilson** [comment]
I think number 4. Thanks!

**Comment by psikoz** [comment]
I sent all the files of number 4 via pullrequest.

**Comment by psikoz** [comment]
You're welcome. If there are any problems, please let me know.

**Comment by samwilson** [comment]
Merged #63. Thanks!
