### ISSUE TITLE
Maximum length when importing CSV

### ISSUE THREAD

**Issue by topkecleon** [tabulate/tabulate#64]
Greetings,

Thank you for your work. I recently inherited a website using your plugin, and I was asked to add a new table from a spreadsheet we use. After stripping it of unnecessary columns and converting it to CSV, the vast majority of the rows have issues being imported. It is telling me that there is a maximum length of 10 characters in a value. This strikes me as odd because we have an existing table containing several thousand values greater than ten characters. What's the deal? Is this a technical limitation uploading from CSV or something else?

All advice greatly appreciated.

Regards,
Drew

**Comment by topkecleon** [comment]
Nevermind, I'm dumb. :)
I didn't define the columns before importing the file, so it was using just the ID column which has a configured max length of 10.

**Comment by samwilson** [comment]
Easily done, don't worry!  :-)

Feel free to raise any other issues you encounter.
