### ISSUE TITLE
How to add a additional MySQL table

### ISSUE THREAD

**Issue by kanted1** [tabulate/tabulate#8]
We have a mysql table and would like to CRUD where to add / config the table . Should we bring it in wordpress DB ? As after installation of tabulate by default it displays the wordpress DB info could not find to change the DB option.

**Comment by samwilson** [comment]
Yes, you must add the tables to the main WP DB in order to manage them with Tabulate. I'll add something to the docs about this.

**Comment by samwilson** [comment]
Done: https://wordpress.org/plugins/tabulate/installation/

Does it read okay?
